name: Docker Image CI

on:
  push:
    branches: [ "main", "feature/cicd" ]
  pull_request:
    branches: [ "main" ]
env: 
  VERSION: 0.0.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: get version
      run: |
        export VERSION=$(node -p "require('./package.json').version")
    - name: get version
      run: |
        echo "version=$VERSION"
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        image: karlosarr/nodejs-web
        push: true
        tags: $VERSION, latest
