name: Docker Image CI/CD

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: set version
      id: vars
      run: |
        echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
    - name: get version
      run: |
        echo "version=${{steps.vars.outputs.version}}"
    - name: Build and push
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        platforms: linux/arm64,linux/amd64
        tags: karlosarr/nodejs-web:${{steps.vars.outputs.version}},karlosarr/nodejs-web:latest
